### ISSUE TITLE
Suggestion: Goodness.ai

### ISSUE THREAD

**Issue by aclearbag** [badnessdotai/catalog#62]
Hey there,
Firstly, although I'm no expert in AI, it seems like there's some really great work going on here! Just wanted to make a suggestion that I've been thinking of for a long while. 

There's a badness.ai to catalogue all the bad things AI can possibly do (and thus help fix those). Could a sister platform (similarly designed) be created to catalogue the good aspects too (goodness.ai)? More specifically, I feel a catalogue of all the known use cases of generative AI would be immensely helpful. The internet is full of people who have discovered things they Generative AI can do (there's literally a linkedin page on [Generative AI](https://www.linkedin.com/company/genai-center/) showcasing these). If this information could be compiled effectively, it would make it much easier for people to become inspired about what the AI tools can do and help raise full awareness about its capabilities. I follow AI news regularly and am amazed by the new tools coming up, but I fail to effectively integrate them into my life – I just never realise "oh, this is something I could get the AI to do and here's how". Having a catalogue like goodness.ai would be helpful. 

What do you think? Am I making sense?

I'd love to start this thing off myself; unfortunately, I'm too caught up in work to take on the big first step!

**Comment by coderrg** [comment]
Thanks for this suggestion! You bring up a really interesting idea. To me, the generative AI startup landscape today is a fairly representative sample of the different positive use cases and capabilities of modern generative AI. There's almost a market incentive to document this "goodness." For example, many folks have put out [comprehensive generative AI market maps](https://ramsrigoutham.medium.com/the-landscape-of-generative-ai-landscape-reports-615a417b15d) that also serve as catalogs of useful, good things that AI systems can do.

On the other hand, there's not much of an incentive to document when things go wrong, even though it's really important for practitioners to learn from mistakes. That's why we focused Badness.ai on that side of the story and structured it as an open-source collaborative catalog.

Let me know what you think!

**Comment by milesmcc** [comment]
Closing for now, but I hope we can keep this conversation going!

**Comment by aclearbag** [comment]
Fair point @coderrg! I didn't think of it from that perspective. Thanks for that link!
